---
# Instructions:
# 1) install ansible 
# 2) install ssh forward-agent so that you can pass your key along for git 
# 3) add hosts you are working with to ansible_hosts file under [setup] section 
# 4) run the following:
# ANSIBLE_SSH_ARGS="-o ForwardAgent=yes" ansible-playbook  -i ansible_hosts_vicci build_vicci.yml --connection=ssh -f 1 -u princeton_jetstream
#
#
#
# This file checks out and build jetstrem on a host. 


### download and build js###
- hosts: setup
  vars:
    js_deps: /jetstream/deps
    js_checkout: /jetstream/js
  tags: build
  tasks:
  - name: copy deploy key
    copy: src=deploy_key dest=/root/.ssh/id_rsa mode=0700
  - name: copy deploy key.pub
    copy: src=deploy_key.pub dest=/root/.ssh/id_rsa.pub mode=0700
  - name: checkout jetstream
    git: repo=git@bitbucket.org:mfreed/jetstream.git dest=${js_checkout}
  - name: make sure jetstream build dir exists
    file: dest=${js_checkout}/build state=directory
  - name: cmake js
    command: cmake -DUSE_CLANG=OFF 
              -DBOOST_ROOT=${js_deps}/boost_1_52_0/ -DBoost_NO_SYSTEM_PATHS=True 
              -DPROTOBUF_LIBRARY=${js_deps}/protobufs/lib/libprotobuf.so 
              -DPROTOBUF_INCLUDE_DIR=${js_deps}/protobufs/include/ 
              -DProtobuf_NO_SYSTEM_PATHS=True 
              -DPROTOBUF_PROTOC_EXECUTABLE=${js_deps}/protobufs/bin/protoc ../
              chdir=${js_checkout}/build
  - name: make js
    command: make
            chdir=${js_checkout}/build
  - name: cp tests data
    command: cp -r src/tests build/src/
            chdir=${js_checkout}
            creates=${js_checkout}/build/src/tests
