---
- hosts: workers  
  accelerate: true
  vars_files:
    - base_vars.yml
  tags: build
  tasks:
  - include: build_include_sudo_ntp.yml
  - include: build_include.yml
  - include: build_include_sudo_mysql.yml
