---
#- hosts: workers
#  gather_facts: no
#  tasks:
#      - action: fireball bind_address=${public_ip}

- hosts: workers  
#  accelerate: true
#  connection: fireball
  vars_files:
    - base_vars.yml
  tags: build
  tasks:
  - include: build_include_sudo_ntp.yml
  - include: build_include.yml
 # - include: build_include_sudo_mysql.yml
