---
# Instructions:
# 1) install ansible 
# 2) install ssh forward-agent so that you can pass your key along for git 
# 3) add hosts you are working with to ansible_hosts file under [setup] section 
# 4) run the following:
# safe: ANSIBLE_SSH_ARGS="-o ForwardAgent=yes" ansible-playbook  -i ansible_hosts_vicci config_vicci.yml --connection=ssh -f 1 -u princeton_jetstream
#
# also works: ansible-playbook  -i ansible_hosts_vicci config_vicci.yml  -u princeton_jetstream
#
#
# This file checks out and build jetstream on a host. 
#  The controller IP address corresponds to sns48


### download and build js###
- hosts: workers
  vars:
    controller_ip: 128.112.7.136
    js_checkout: /jetstream/js
  tasks:
  - name: vicci_config
    template: src=vicci_config.j2 dest=${js_checkout}/config/vicci.conf
