---
- hosts: workers
  vars_files:
    - base_vars.yml
  tasks:
  - name: make sure jetstream data dir exists
    file: dest=${js_data} state=directory
  - name: copy coral data to servers
    copy: src=/disk/local/jetstream_data/coral_ordered/${server_index}.log.gz dest=${js_data}/coral.log.gz
  - name: unzip coral data
    command: gunzip coral.log.gz
            chdir=${js_data}
            creates=${js_data}/coral.log
